# Generated by Django 3.1.6 on 2021-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='content',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='title',
        ),
        migrations.AddField(
            model_name='wish',
            name='Details',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
